---
ID: "3e815c06-c24c-497c-84c1-6a10c1b04d5a"
Parent: "edfe26d8-7c98-4e72-82bb-8b6a732ec8dd"
Template: "edfe26d8-7c98-4e72-82bb-8b6a732ec8dd"
Path: /sitecore/templates/Project/Hackathon/Page Design/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210306T133127Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
